---
title: The Psychology of Persuasion, Revised Edition
author: Robert B. Cialdini
date: 2006 (1984)
draft: true
---

> Compliance: What are the factors that cause one person to say yes to another person?

1. Reciprocation
2. Commitment and Consistency
3. Social Proofs
4. Linking
5. Authority
6. Scarcity

## 1. Weapons of Influence

Ethology - study of animal behavior under natural conditions.

Turkey moms, chicks' chirp-chirp and toys with similar sound. Fixed-action pattern, trigger feature.

Can you do me a "favor", because I have a "reason". Better when compelling, but bogus also works (cutting the line to a xerox because "I need to make a few copies").

Automatic behavior (birds mating based on sound or prominent features). Exploitation vs symbiosis.

"Automatic, stereotyped behavior is prevalent in much of human action, because in many cases it is the most efficient form of behaving".

Meta-manipulation: ability to manipulate without the appearance of manipulation.

**Perceptual contrast** principle: light-heavy, hot-cold, beautiful-ugly, cheap-expensive. All perceptions are **relative**!

Tailor with "hearing problem". Customer asks how much, tailor shouts to another man how much, then tells to customer lower price. Expensive == Good.

Sell high priced item first (ex. suite), then add "accessories" (ex. expensive shirt).

Show "expensive" crap first, then the one you actually want to sell (used cars salesmen, real estate agents).


## 2. Reciprocation

Gifts, favors and services trigger reciprocation response. It seems to be a universal behavior across human cultures. (What about grooming in monkeys?)

"The rule (of reciprocation) says that we should try to repay, in kind, what another person has provided us."
"much obliged" == "thank you".

Examples: Hare Krishnas; give a flower, then ask for donation. Amway: free samples (shampoo, insect spray), then sales.

**Reciprocal concession**: "Salesman" ask you to buy something outrageously expensive. You refuse. "Salesman" asks you to buy something much cheaper instead (actually the original goal of the salesman). You agree! (combination of reciprocation and perceptual contrast). Technique also used by negotiators. 

Another name for "reciprocal concession" is "rejection then retreat". 


## 3. Commitment and Consistency

## 4. Social Proofs

## 5. Linking

## 6. Authority

## 7. Scarcity

