---
title: The Psychology of Persuasion, Revised Edition
author: Robert B. Cialdini
date: 2006 (1984)
draft: true
---

> Compliance: What are the factors that cause one person to say yes to another person?

1. Reciprocation
2. Commitment and Consistency
3. Social Proofs
4. Linking
5. Authority
6. Scarcity

## 0. Weapons of Influence

Ethnology, turkeys, cheep-cheep toys, fixed-action pattern (tape record, mating), trigger feature.

Can you do me a "favor", because I have a "reason" (better when compelling).

Automatic behavior, rules of thumb, exploitation vs symbiosis.

Tailor with "hearing problem". customer asks how much, tailor shouts to another men how much, then tells to customer lower price. expesive == good.

Meta-manipulation: ablity to manipulate without the appearance of manipulation.

Perceptual contrast principle: light-heavy, hot-cold, beautiful-ugly.
Sell high priced item first, then add "accessories" (expensive).
Show crap first, then expensive one.


## 1. Reciprocation

## 2. Commitment and Consistency

## 3. Social Proofs

## 4. Linking

## 5. Authority

## 6. Scarcity

