---
title: How To Think More About Sex
author: Alain De Botton
date: 2012-05-01
categories: [psychology, culture]
---

# I. Introduction

> It is rare to get through this life without feeing that we are somehow a bit odd about sex.

> Despite being one of the most private of activities, sex is nonetheless surrounded by a range of powerful socially sanctioned ideas that codify how normal people are meant to feel about and deal with the matter.

> Whatever discomfort we de feel around sex is commonly aggravated by the idea that we belong to a liberated age -- and ought by now, as a result, to be finding sex a straightforward and untroubling matter.

pre-religious society, religious society, 1920's - 1960's "sexual liberation", bikinis, talk about masturbation and bdsm, watching pornography...

> ...sex is not something that we can ever expect to feel easily liberated from.

there is a reason why it was and still is a taboo subject in many social contexts.

> it (sex) is a fundamentally disruptive, overwhelming and demented force, strongly at odds with the majority of our ambitions and all but incapable of being discreetly integrated within civilized society.

> It refuses to sit neatly on top of love, as it should.


# II. The pleasures of sex
## 1. Eroticism and Loneliness

Evolutionary biology, genetically programmed for reproduction, pleasures of sex as a reward for undertaking the immense efforts of raising children

But evolutionary biology doesn't really provide us with a very satisfactory account of why sex should really matter to us as reflexive humans.

Memories of first or new encounter with someone exhibiting reciprocal interest, first kiss... Relation to child-mother, unconditional acceptance, tenderness and love with a lot of physical contact. Gradually there is a separation, covering of the body, adolescence, social and cultural norms, public and private self, shame.

> We grow into clumsy, heavy-footed, shameful, anxious creatures. We become adults, definitively expelled from paradise. But deep inside, we never quite forget the needs with which we were born: to be accepted as we are, without regard to our deeds; to be loved through the medium of our body; to be enclosed in another’s arms.


### The Kiss -- Acceptance

> It could sound disgusting, and that’s the point. Nothing is erotic that isn’t also, with the wrong person, revolting, which is precisely what makes erotic moments so intense.


### The Undressing -- An end to shame

> The shame begins in adolescence... A division begins between our ordinary public selves on the one hand and our sexual and private identities on the other. A large portion of who we are as adults, from our sexual fantasies to our parted legs, becomes impossible to share with almost anyone we know.

sexual fantasies clash with what we think is proper and expected behavior (from family and society).


### Excitement -- Authenticity

> Erections and lubrication simply cannot be effected by willpower and are therefore particularly true and honest indices of interest.


### Rudeness -- Love

> It can be a sign of love to be allowed to slap someone hard across the face or to clasp our hands forcefully around another’s neck... It doesn’t matter to them (partner) that we have darker sides;  they can -- like the ideal parent -- see us whole and recognize us as being fundamentally good.

> When we are on the receiving end of this type of violence and rudeness, we may find a parallel pleasure, and a certain sense of strength, in being able to decide for ourselves just how insulted, hurt and dominated we are going to feel.


### Fetishism -- Goodness

> We will be drawn to specific things either because they recall appealing qualities of a beloved parental figure or else, conversely, because they somehow cancel out, or otherwise help us to escape, a memory of early humiliation or terror.

Deep, semi-conscious memories that might indicate/confirm an ideal partner.

> They turn us on because they are emblems of the Good.


### Orgasm -- Utopia

> The more closely we analyze what we consider "sexy", the more clearly we will understand that eroticism is the feeling of excitement we experience at finding another human being who shares our values and our sense of the meaning of existence.

> The orgasm itself marks the supreme moment when our loneliness and alienation are momentarily overcome. Everything we have appreciated about our lover [...] are combined into a concentrated distillation of pleasure that leaves each partner feeling uniquely tender towards and vulnerable with the other.

> Post-coital sadness often settles over a couple.

> ...it [sex] is an ecstasy we feel at encountering someone who may be able to put to rest certain of our greatest fears, and with whom we may hope to build a shared life based upon common values.


## 2. Can 'Sexiness' Be Profound?

Attraction based purely on physical appearance.
Biology: beauty is a promise of health and healthy offsprings.
Cross-cultural studies: beauty == symmetry, balance, right proportions.
Stendhal: beauty is a promise of happiness. How much can we "read" from a portrait?
Clothes and expression/suggestion of values.


## 3. Natalie or Scarlett?

> The specifics of what we find "beautiful" and what we find "sexy" are indications of what we most deeply crave in order to rebalance ourselves.


## III. The problems of Sex
## 1. Love and Sex

> We tend to tiptoe around what we want, cloaking our needs with evasions and in the process, we habitually lie, break others’ hearts and suffer through evenings filled with frustration and guilt.

Direct expression of pure sexual desire or pure love are equally problematic and force both parties to lie (not tell the whole truth).

> ...wanting love more than sex, or even instead of it, isn’t "better" or "worse" than the reverse.


## 2. Sexual Rejection

> Rejection hurts so much because we take it as a damning judgement passed not merely on our physical appeal but on our entire selves, and by extension on our very right to exist.


## 3. Lack of desire

> Eroticism seems, in the end, to have very little to do with simply being unclothed: it springs instead from a promise of mutual arousal...

> Suffering sexual rejection by the person with whom we have pledged to share our life is a much odder and more humiliating experience.

> ...the paucity of sex within established relationships typically has to do with the difficulty of shifting registers between the everyday and the erotic.

Freud, child-parent love, taboo, children after marriage, mummy-daddy...

> The solution to long-term sexual stagnation is to learn to see our lover as if we had never laid eyes on him or her before.
