---
title: Why We Sleep
author: Mathew Walker
date: 2017-10-03
categories: [brain, health]
---


## 1: To Sleep

Chronic lack of sleep (less than 8hrs) is associated with higher risk of getting cancer, diabetes, cardiovascular diseases, and psychiatric diseases.

Sleeping (1/3 of total time) is a natural drive/need, like eating, drinking and reproduction.

Sleep does a sort of full body reset: memory consolidation, emotional state,
immune and cardiovascular systems, appetite.


## 2: Caffeine Jetlag and melatonin

Circadian rythm generated by supra-chiasmatic nucleus (core body temperature oscillation).

Mammoth Cave experiment: humans natural cycle is 24h15m

SCN releases melatonin which signals "night time", but M is not an active "sleepiness" agent. Sleeping pressure is the result of adenosine buildup in the brain. Caffeine blocks adenosine receptors, creating an illusion of alertness (half-time is 6 hrs depending on individual liver enzyme which breaks caffeine).


## 3. Defining and Generating sleep

Polysomnography: 1) brainwave activity 2) eye movement activity 3) muscle activity.

REM and NREM sleep (1957), NREM has 4 stages. Humans go from wake to REM to NREM 1, 2, 3 and 4. Phase 3 and 4 are deep sleep (hardest to wake the person up). During the night we have 5-6 cycles of REM/NREM phases of ~1.5hrs. Duration of REM phase increases during later cycles.

Removing (pruning) of unnecessairy neural connections during the NREM, strengthening existing connections during REM. During REM, brain activity is very close to awake state (fast, no sync between regions). During NREM there are slow syncronized waves. Loss of consciousness and the sense of time during sleep is because of inhibition of sensory information flow through thalamus during sleep.

During NREM we transfer memories from short term to long term storage (reason why we need syncronization across regions).

Dreaming during REM is probably like a replay and check of memories after they have been modified during NREM phase. During REM phase the body is completely paralyzed (except for involuntary movement like breathing) again through thalamus to avoid motor activity due to dreaming (evolutionary, avoid dropping from trees while sleeping).


## 4. Ape beds, dinosaurs, and napping with half a brain

Every animal and bird species studied sleep including fish and insects. Even invertebrates like mollusks and worms have periods of slumber, i.e. sleep evolved during Cambrian explosion 500 mil years ago or wakefullness evolved from default sleep mode.

Huge variability of sleep duration and pattern across animals, from 4 to 19hrs/day. Size and complexity of the nervous system vs body mass have a weak correlation with sleep patterns. REM seems to exist only in mammals and birds.
Aquatic animals (including mammals) don't have REM sleep as we know it; pinnipeds (seals) have REM only when on land. Natural human sleep pattern is likely bi-phasic (like in siesta cultures): long night and short nap in the afternoon. MID-night.


## 5. Changes in sleep across the life span

Before birth: embryos sleep most of the time and have lot's of REM sleep. Over-generation of synaptic connections. Alcohol disurupts it, including when lactating after birth. 

Newborns spend lots of time sleeping (polyphasic sleep), progressively getting into bi-phasic (SCN development, after 3yo) and mono-phasic (after 6 yo).

Adolescents have their natural circadian cycle shift to later than adults, i.e. they can't sleep early and wake up early.

Elderly: fragmented sleep


## 6. The benefits of sleep for the brain

Sleep before learning refreshes our ability to make new memories (because transfer from short term memory in hippocampus to long term memory in the cortex) (during light NREM, spindles?).

Sleep after learning consolidates fact-based memory (during NREM sleep). Sleep also helps recover "lost" memories. Sleep also help to forget "unwanted" memories.

There is no such thing as "muscle memory". Sleep also help consolidating motor-skill based memories.

Chronic lack of sleep is correlated with higher risk of injury in competitive athletes.

p 280 (creativity).
...


