---
title: Becoming a Technical Leader
author: Gerald M. Weinberg
date: 1986-01-01
categories: [psychology, coaching, technology]
---


### Ch 1. What is Leadership, Anyway?

> Leadership is like sex. Many people have trouble discussing the subject, but it never fails to arouse intense interest and feelings.

> People who look really sexy are often great disappointments when it comes to actual performance. It’s the same with people who look like leaders.

Models: linear and organic perception of events, people, relationships and attitude towards change. Threat/reward (judge, force) vs seed (choose and discover).


### Ch 2. Models of Leadership Style

MOI model: Motivation, Organization, Innovation (Ideas). Can be used to enable or discourage growth.

What technical leaders do? Understanding the problem, managing the flow of ideas, maintaining quality.

> problem-solving leaders have one thing in common: a faith that there’s always a better way.
> ... faith is the belief in something for which there is no proof (Russell).

Unless and until all members of a team have a common understanding of the problem, attempts to solve the problem are just so much wasted energy.

No worthwhile project is ever described fully and correctly...

Large problems require the joint effort of many people working in harmony.

All great chefs taste the food during preparation (on maintaining quality).

Above all, leaders are leaders of change in themselves.

...spend some time mastering tactics, but don’t forget to look for a better strategy (on growth; graph: slow improvement, dip, rapid growth, new plateau)

It’s hard to see the climate when you’re experiencing the weather.

Models and other descriptions can tell what happens on the outside, but not how it feels when it happens.

Feelings are much more reliable than factual details.

The threat/reward model may say that change comes from the top, but my experience tells me that change starts with what we choose to have for breakfast.


## Ch 6. The three great obstacles to innovation

1. Self-blindness. The inability to see ourselves as others see us is the number one obstacle to self-improvement. ("The only way we can see ourselves is through other people).
2. No problem syndrome (when people don't want to hear what's the actual problem and offer a "solution")
3. Belief in the existence of only one correct solution to a problem.


## Ch 7. A tool for developing Self-Awareness

Journaling


## Ch 8. Developing idea power

> In some sense, the only truly original ideas come from mistakes.


## Ch 9. The Vision

> People don't become leaders because they never fail. They become leader because of the way they **respond** to failure.

