---
title: "Sand Talk: How Indigenous Thinking Can Save the World"
author: Tyson Yunkaporta 
date: 01/01/2019
date-format: "YYYY"
format:
  html:
    toc: true
    toc-depth: 2
categories: [culture, complexity]
---


> Solutions to complex problems take many dissimilar minds and points of view.

Connective thinking.


# Albino boy

( < > ) knee bend direction, "I am greater/lesser than you"

> Containing the excesses of malignant narcissists is a team effort... Engaging with them (narcissists) alone is futile -- never wrestle a pig -- as the old saying goes; you both end up covered in shit, and the pig likes it.

> The basic protocols of Aboriginal society, like most societies, include respecting and hearing all points of view in a yarn. Narcissists demand this right, then refuse to allow other points of view on the grounds that any other opinion somehow infringes their freedom of speech or is offensive.

> Everyone is an idiot from time to time.


# First Law

(three circles and flowers)

> After my yarns with Percy, I begin to see the uncertainty principle not as a law but as an expression of frustration about the impossibility of achieving godlike scientific objectivity.


# Forever limited

> Sustainable systems cannot be manufactured by individuals or appointed committees, particularly during times of intense transition and upheaval.

> Ideas can be re-engineered to serve the interests of the powerful.

(chekout Larry Gross, Post Apocaliptic Stress Syndrom).


# Lines in the sand

> People today will mostly focus on the points of connection, the nodes of interest like stars in the sky. But the real understanding comes in the spaces in between, in the relational forces that connect and move the points.

> Systems are **heterarchical** -- composed of equal parts interacting together. Imposing a hierarchical model of top-down control can only destroy them. Healthy interventions can only be made by free agents within a complex system.

> On learning another culture (cultural humility): 1) Check your ego and motives, 2) You don't need to be an expert to understand the knowledge process of people from other cultures and enter into dialogues with them (but you need to show respect), 3) Making yourself an expert in another culture is not always appreciated by the members of that culture.

> It is difficult to relinquish the illusions of power and delusions of exceptionalism that come with privilege. But it is strangely liberating to realise your true status as a single node in a cooperative network.

> Sustainable systems cannot function without the full autonomy and unique expression of each independent part of the interdependent whole.

> Sustainability agents have a few simple operating guidelines, or network protocols, or rules if you like -- connect, diversify, interact and adapt.

> An agent that is truly adaptive and changing is open to sudden eruptions of transformation.

> Not all strange attractors are benevolent (narcissist).

> Adolescent cultures always ask the same three questions. Why are we here? How should we live? What will happen when we die?


# Of Spirit and Spirits

> There are at least four parts to your spirit from an Aboriginal point of view: your higher self (superego), ancestral spirit, living spirit and shadow spirit... Your shadow spirit is that part of you that wants things you don't need, makes you think you're better than other people and above the land. If the rest of your spirit is not clear and in balance, it gets away from you, causing conflict and destruction. You gossip behind people's backs, spread uncertainty, deliver judgments, upset people, take more than you need and accumulate goods without sharing. It makes you a competitor instead of a human being.

```
                   =     metaphors   
                //   \\    
abstract       o      o   concrete
                \\   //
                   =    metaphors
```

> There is a spark of creation like lightning when true learning takes place, with a genetic reward of chemical pleasure released in the brain... The chemical burst of pleasure we feel when genuine knowledge transmission takes place occurs from the creation of new neural pathways. These are connections between two points that were previously unconnected. Jokes are one of the most pure examples of this neural creation event... If people are laughing, they are learning.

> There needs to be an interaction between abstract (spirit) and concrete (physical) worlds of knowledge for this kind of complexity to develop fully.

> Without closing the loop between abstract knowledge and reality, and without making connections between different ideas and areas of knowledge, true learning cannot occur.

> A focus on linear, abstract, declarative knowledge alone not only fails to create complex connectivity but damages the mind. We are biologically punished for this destructive behaviour with a neuro-chemical rush of lethargy and discomfort that most people call boredom.

> Knowledge transmission must connect both abstract knowledge and concrete application through meaningful metaphors to be effective.


# Advanced and Fair

TODO
